### PR TITLE
Otter docker test suite ubuntu and ensembl update

### PR DESCRIPTION
**Pull request by shashankbrgowda**
Otter docker test suite ubuntu and ensembl update
- Update ensembl version to 108
- Update Ubuntu version to 22.04

### CODE REVIEW

**Review by mira13 — CHANGES_REQUESTED** [review]
Would you please add docker file to misc-otter repo, otherwise its hard to review without seeing changes

**Comment by shashankbrgowda** [comment]
> Would you please add docker file to misc-otter repo, otherwise its hard to review without seeing changes

Here is the PR for that repo - https://github.com/Ensembl/misc-otter-files/pull/12

**Comment by mira13** [comment]
Please put zmap and seqtools installation either back to image or here to travis build. Even they are not requered for test perl suite - we can't say that we migrated otter without having zmap and seqtools installed.

**Review by mira13 — APPROVED** [review]
Looks good to me

**Pull request merged**
