### PR TITLE
Revert "Revert "Store evidences""

### PR DESCRIPTION
**Pull request by s-mm**
Reverts Ensembl/ensembl-otter#107

### CODE REVIEW

**Comment by s-mm** [comment]
@mira13 The error messages/ warnings need to change. Also, I'm not sure if the formatting is correct.

**Comment by mira13** [comment]
@smm what exactly is wrong with error/warning msgs?

**Comment by s-mm** [comment]
@mira13 I'm not sure the code should have warning like  warn('NOT SURE WHAT TO DO NOW'); or warn(' TDONE'); or warn(' GETTING ATTRIBUTES'); or warn('WEIRD it was cut to fit'); or warn('WEIRD: a sub object could not be transfered to the target_slice');  or warn('This does not fit here'); or warn('WEIRD: a sub object could not be transfered to the target_slice');. Please review the formatting too.

**Comment by mira13** [comment]
@smm 
such unique msgs allow quickly catch them in the huge otter log.   for testing pruposes they should stay there, after testing is finished - i will remove whatever is seemed wrong for you

**Comment by s-mm** [comment]
Approving for now. The warnings and formatting will have to be reviewed again before merging in master branch.

**Pull request merged**
