### PR TITLE
Code to handle clone fetching from the assembly level.

### PR DESCRIPTION
**Pull request by s-mm**
Code to handle ENSCORESW-2978.
The code has two ways of fetching the clones from the assembly. The preferred method is to use the get_MiscFeatureAdaptor. There is a difference in number of clones fetched by the SQL query and the adaptor.

### CODE REVIEW

**Comment by mkszuba** [comment]
Personally I do not see much of a speed improvement, not on my database anyway - but this also fixes the spillover of clone locks so it is very much desired.

**Comment by s-mm** [comment]
@mkszuba I modified the original query with the clause 'AND ctg.length > 20000' to get a list of clones quickly. If you remove the clause, you will see the difference in performance. Fair warning- the original script takes about 10 minutes to process.

**Comment by mkszuba** [comment]
Lock spillover is still gone, on the new database at least (haven't tried with the old one this time).

**Comment by mkszuba** [comment]
Now that's interesting - I forgot to mention but when half an hour ago I tried opening the list of clones for chromosome 14 using the restored original query and the new database it was in fact quite fast, in the order of 10 seconds. For the old database, which I have just tried again, the same does make the client lock up for at least 5 minutes (don't know how long exactly it took because I walked away from the computer).

**Pull request merged**
