### PR TITLE
Bugfix/save transcript

### PR DESCRIPTION
**Pull request by s-mm**
ENSCORESW-3189- Code to save the new annotation or change in annotation in the local DB and on Loutre DB. 

The ticket is resolved by merging the code in PR #59 and PR #63.

### CODE REVIEW

**Comment by thibauthourlier** [comment]
For ...::XML::Region, is there a reason for calling Bio::Otter::ServerAction::LoutreDB instead of a $odba->get_CoordSystemAdaptor to retrieve the database coordinate system?
Or could $odba be given as to CoordSystemAdaptor with -dba?

**Comment by s-mm** [comment]
@thibauthourlier It can be done but is there an easier way to get the coord_system for all levels than the one in LoutreDB.pm? I would be mostly repeating code from LoutreDB.pm

**Comment by thibauthourlier** [comment]
If you really need all the coordinate systems then probably no, if you only need the toplevel coord system then just calling fetch_by_name(name, version) from CoordSystemAdaptor would be enough

**Comment by s-mm** [comment]
I'm caching all the coordinate systems as that seems to solve all further issues with coord_system when the local dba is not available.

**Pull request merged**
